// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddToCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addToCart() {
    driver.get("https://eu.defacto.com/pages/women");
    driver.manage().window().setSize(new Dimension(1060, 800));
    js.executeScript("window.scrollTo(0,536.7999877929688)");
    driver.findElement(By.linkText("Coats")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".grid__item:nth-child(1) .grid-product__secondary-image"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".grid__item:nth-child(1) .grid-product__secondary-image")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,152.8000030517578)");
    driver.findElement(By.id("AddToCart-6891822383264")).click();
    driver.findElement(By.cssSelector(".dropdown-element:nth-child(2)")).click();
    driver.findElement(By.id("AddToCart-6891822383264")).click();
    driver.findElement(By.cssSelector(".drawer__close:nth-child(2) path")).click();
    driver.findElement(By.id("MainContent")).click();
    driver.findElement(By.linkText("Clothing")).click();
    js.executeScript("window.scrollTo(0,151.1999969482422)");
    driver.findElement(By.linkText("Skirts")).click();
    driver.findElement(By.cssSelector(".grid__item:nth-child(2) > .grid-product__content .grid-product__secondary-image")).click();
    driver.findElement(By.id("AddToCart-7108683595936")).click();
    driver.findElement(By.cssSelector(".dropdown-element")).click();
    driver.findElement(By.id("AddToCart-7108683595936")).click();
    driver.findElement(By.cssSelector(".drawer__close:nth-child(2) .icon")).click();
    driver.findElement(By.linkText("Clothing")).click();
    driver.findElement(By.linkText("Jeans")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".grid-product__image-mask > .lazyloaded:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".grid__item:nth-child(2) > .grid-product__content .grid-product__secondary-image")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,79.19999694824219)");
    driver.findElement(By.cssSelector(".selected-variant")).click();
    driver.findElement(By.cssSelector(".dropdown-element:nth-child(2)")).click();
    driver.findElement(By.id("AddToCart-7127175823520")).click();
  }
}
