// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CheckColourTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkColourTest() {
    driver.get("https://eu.defacto.com/collections/women-t-shirts");
    driver.manage().window().setSize(new Dimension(1062, 800));
    js.executeScript("window.scrollTo(0,184)");
    js.executeScript("window.scrollTo(0,847.2000122070312)");
    driver.findElement(By.cssSelector("#CollectionSidebar-1 .color-swatch--green")).click();
    js.executeScript("window.scrollTo(0,217.60000610351562)");
    {
      WebElement element = driver.findElement(By.linkText("Jumpsuits"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".grid__item:nth-child(5) .grid-product__secondary-image")).click();
    js.executeScript("window.scrollTo(0,188.8000030517578)");
  }
}
