package Testovi;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashMap;
import java.util.Map;

//Generated by Selenium IDE
import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class RegisterTest {
	  private WebDriver driver;
	  private String
	  exePath=
			  "C:\\Users\\HP\\OneDrive\\Desktop\\Testiranje DeFacto\\chromedriver.exe";
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  @BeforeEach
	  public void setUp() {
		 System.setProperty("webdriver.chrome.driver", exePath);
	    driver = new ChromeDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	  }
	  @AfterEach
	  public void tearDown() {
	    driver.quit();
	  }
	  @Test
	  public void login() {
	    driver.get("https://eu.defacto.com/account/register");
	    driver.manage().window().setSize(new Dimension(1536, 816));
	    driver.findElement(By.cssSelector(".small--hide > .icon")).click();
	    driver.findElement(By.id("customer_register_link")).click();
	    driver.findElement(By.id("FirstName")).sendKeys("Ivana");
	    driver.findElement(By.id("LastName")).click();
	    driver.findElement(By.id("LastName")).sendKeys("Perisic");
	    driver.findElement(By.id("Email")).click();
	    driver.findElement(By.id("Email")).sendKeys("ivanaperisic84@gmail.com");
	    driver.findElement(By.id("CreatePassword")).click();
	    driver.findElement(By.id("CreatePassword")).sendKeys("Ivanap.00");
	    driver.findElement(By.cssSelector(".btn--full")).click();
	  }
	}